export { AddCircle } from './AddCircle'
export { People } from './People'
export { Person } from './Person'
export { Award } from './Award'
export { BriefCase } from './BriefCase'
export { EmailCircle } from './EmailCircle'
export { GridView } from './GridView'
export { Message } from './Message'